FROM tensorflow/tensorflow:latest-py3
MAINTAINER Pili

# Installation des dépendances standards
RUN apt-get update && apt-get install -y --no-install-recommends curl wget nano apt-transport-https lsb-release ca-certificates

# Installation de TK
RUN apt-get install -y --no-install-recommends python3-tk

# Mise à jour de pip
RUN pip install --upgrade pip

# Installation de tensorflow-hub
RUN pip install tensorflow-hub

# Installation du connecteur MySQL
RUN apt-get update && apt-get install -y --no-install-recommends libmysqlclient-dev
RUN pip install mysql-connector

# Lancement de Python
RUN echo "#!/bin/bash" > /home/pysemantic.sh &&\
	echo "cd /notebooks/semantic" >> /home/pysemantic.sh &&\
	echo "python main.py" >> /home/pysemantic.sh

RUN echo "#!/bin/bash" > /home/endpoint.sh &&\
	echo "while [[ 1 ]]; do" >> /home/endpoint.sh &&\
	echo "sleep 10" >> /home/endpoint.sh &&\
	echo "done" >> /home/endpoint.sh

CMD [ "/bin/bash", "/home/endpoint.sh" ]