FROM tensorflow/tensorflow:latest-py3
MAINTAINER Pili

# Installation des dépendances standards
RUN apt-get update && apt-get install -y --no-install-recommends curl wget nano apt-transport-https lsb-release ca-certificates

# Installation de TK
RUN apt-get install -y --no-install-recommends python3-tk

# Mise à jour de pip
RUN pip install --upgrade pip

# Installation de tensorflow-hub
RUN pip install tensorflow-hub

# Installation du connecteur MySQL
RUN apt-get update && apt-get install -y --no-install-recommends libmysqlclient-dev
RUN pip install mysql-connector

# Installation du connecteur MongoDb
RUN pip install pymongo

# Installation du pack fr
RUN apt-get install -y --no-install-recommends locales &&\
	locale-gen en_CA.UTF-8 &&\
	echo "environment=LANG=\"es_ES.utf8\", LC_ALL=\"es_ES.UTF-8\", LC_LANG=\"es_ES.UTF-8\"" > /etc/default/locale
RUN chmod 0755 /etc/default/locale
ENV LC_ALL=en_CA.UTF-8
ENV LANG=en_CA.UTF-8
ENV LANGUAGE=en_CA.UTF-8

# Lancement de Python
RUN echo "#!/bin/bash" > /home/pysemantic.sh &&\
	echo "export LANG=en_US.UTF-8" >> /home/pysemantic.sh &&\
	echo "cd /notebooks/semantic" >> /home/pysemantic.sh &&\
	echo "python main.py" >> /home/pysemantic.sh

RUN echo "#!/bin/bash" > /home/endpoint.sh &&\
	echo "while [[ 1 ]]; do" >> /home/endpoint.sh &&\
	echo "sleep 10" >> /home/endpoint.sh &&\
	echo "done" >> /home/endpoint.sh

CMD [ "/bin/bash", "/home/endpoint.sh" ]